; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = 
	adafruit/Adafruit INA219 #@^1.2.3
	mirs240x/micro_ros_arduino@^2.0.7-humble
	
upload_speed = 921600
monitor_speed = 921600

monitor_filters = esp32_exception_decoder 
# use the microros precompiled library 
build_flags = 
	-I.pio/libdeps/wemos_d1_mini32/micro_ros_arduino/src
	-L uros-precompiled-lib
	-llibmicroros.a

# Enable OTA upload
upload_protocol = espota
upload_port = 192.168.1.208

board_build.partitions = min_spiffs.csv

[env:native]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
test_ignore = test_blinker
test_build_src = false

lib_deps = 
	adafruit/Adafruit INA219 #@^1.2.3
	mirs240x/micro_ros_arduino@^2.0.7-humble

build_flags = 
	-I.pio/libdeps/wemos_d1_mini32/micro_ros_arduino/src
	-L uros-precompiled-lib
	-llibmicroros.a